### ISSUE TITLE
Doesn't pass egui color test

### ISSUE THREAD

**Issue by derivator** [t18b219k/egui_vulkano_backend#1]
Hey! I've been working on a simple [vulkano backend for egui](https://github.com/derivator/egui_vulkano) as well :sweat_smile: I just tried your example and noticed it doesn't pass the color test on my machine:
![Color test](https://user-images.githubusercontent.com/2171264/110304021-5edd1c80-7ffb-11eb-9f21-c380a9931290.png)

I was able to fix the colors by setting the swapchain format like this
```rust
assert!(&caps
  .supported_formats
  .contains(&(Format::B8G8R8A8Srgb, ColorSpace::SrgbNonLinear)));
let format = Format::B8G8R8A8Srgb;
```

instead of `caps.supported_formats[0].0`

Don't know what's going on with the texture gradients. Anyway, I'd love to have a chat about some of the decisions you've made. For example, it seems you're creating a new `CpuAccessibleBuffer` for every mesh? When I tried that I got horrible performance, but I must have been doing something wrong because your demo app seems to run fine...

**Comment by KentaTheBugMaker** [comment]
okay I tested egui_wgpu_backend like way but i cant pass vulkano validation so horrible way in current

**Comment by KentaTheBugMaker** [comment]
may be pipeline setting ?

**Comment by KentaTheBugMaker** [comment]
problem caused from renderpass?

**Comment by KentaTheBugMaker** [comment]
ok I found problem on allocating new texture 

new image arrived User(0)
new image arrived User(2)
new image arrived User(4)
new image arrived User(6)
new image arrived User(8)
new image arrived User(10)
new image arrived User(12)
new image arrived User(14)
new image arrived User(16)
new image arrived User(18)
new image arrived User(20)
new image arrived User(22)
new image arrived User(24)
new image arrived User(26)
new image arrived User(28)
new image arrived User(30)
new image arrived User(32)
new image arrived User(34)

**Comment by KentaTheBugMaker** [comment]
ok fixed it
